---
# Install multics and it's dependencies on ubuntu
- name: Install multics
  gather_facts: false
  hosts: server1
  vars:
    - multics_archive: multics-r82-hellboy-V14-beta-dirty.zip
    - multics_dest: /usr/local/bin/
    - multics_bin: multics.x64
    - check_version_installed: Multi CardServer r82-hellboy-V17-beta-41-g138227f based on the work by evileyes (http://www.infosat.org)
  tasks:
    - block:
      - name: Update cache and install required packages
        apt:
          update_cache: true
          name: '{{ item }}'
        with_items:
          - libc6-dev
          - daemontools
          - daemontools-run
          - lighttpd
          - dos2unix
          - bsdtar
       
    - block:
      - name: Extract {{ multics_archive }} into {{ multics_dest }}
        unarchive:
          src: './files/{{ multics_archive }}'
          dest: {{ multics_dest }}
          mode: 0755
          list_files: true
      - name: Create multics conf dir
        file: 
          path: '/var/etc/'
          state: directory
      - name: Transfer startup file to destination
        copy:
          src: './files/run'
          dest: '/etc/service/multics/'
          directory_mode: true
          mode: 1755
      - name: Transfer logrotate file to destination
        copy:
          src: './files/multics'
          dest: '/etc/logrotate.d/'

    - block:
      - name: Setup lighttpd conf
        replace:
          path: '/etc/lighttpd/lighttpd.conf'
          regexp: '{{ item[0] }}'
          replace: '{{ item[1] }}'
        with_together:
          - [ '^server.document-root        = "/var/www/html"$', '^server.port                 = 80$' ]
          - [ 'server.document-root        = "/var/www/manager"', 'server.port                 = 50080' ]
      - name: Setup fastcgi symlinks
        file:
          src: '{{ item[0] }}'
          dest: '{{ item[1] }}'
          state: link    
        with_together:
          - [ '/etc/lighttpd/conf-available/10-fastcgi.conf', '/etc/lighttpd/conf-available/15-fastcgi-php.conf' ]
          - [ '/etc/lighttpd/conf-enabled/10-fastcgi.conf', '/etc/lighttpd/conf-enabled/15-fastcgi-php.conf' ]
          
    - block:
      - name: Setup chrotabs
        blockinfile:
          path: '/etc/crontab'
          block: |
            0 7 * * *      root    python /root/epg/epg_grab.py
            0 9 * * *       root    wget -qO- software77.net/geo-ip/?DL=2 | bsdtar -xf- -C /var/etc/
            0 4 * * *       root     /var/www/manager/script/check_fline_restart_cccam
            0 0 * * *       root     php /var/www/manager/multicache.php > /dev/null
      
    - block:
      - name: Force stop running multics
        shell: 'killall -9 {{ multics_bin }}'
      - name: Check new version installed
        command: '{{ multics_bin }} -h'
        register: multics_version
      - name: Assert correct version installed
        assert:
          that:
            - "'{{ check_version_installed }}' in multics_version.stdout"
            
    - block:
      - name: Flush existing firewall rules
        iptables:
          flush: true
          
      - name: Firewall rule - limit ports access
        iptables:
          chain: INPUT
          protocol: tcp
          source: '{{ item[0] }}'
          destination_port: '{{ item[1] }}'
          jump: ACCEPT
        loop: "{{ [sp_host, amd_host, cc_host, api_host, telnet_host]|zip([sp_port, amd_port, cc_port, api_port, telnet_port])|list }}"
          
      - name: Firewall rule - limit outside access
        iptables:
          chain: INPUT
          protocol: tcp
          source: '0.0.0.0/0'
          destination_port: '{{ item }}'
          jump: DROP
        loop:
          - '{{ sp_port }}'
          - '{{ amd_port }}'
          - '{{ cc_port }}'
          - '{{ api_port }}'
          - '{{ telnet_port }}'
          
      - name: Install netfilter-persistent and iptables-persistent packages
        package:
          name: "{{item}}"
          state: present
        loop:
          - iptables-persistent
          - netfilter-persistent

...